### ISSUE TITLE
EBDB mangles a particular name

### ISSUE THREAD

**Issue by wyleyr** [girzel/ebdb#106]
I'm new to EBDB and I've encountered a weird bug when entering a contact: entering the name "Reddemann" as a contact's (last) name consistently causes EBDB to split it up and duplicate "Redde", producing "Redde Redde mann". This a contact with a German address; I have the ebdb-i18n package loaded.

I've experimented a bit and see:
- "Redemann" gets  mangled to "Rede Rede mann"
- "Redde" gets mangled to "Redde Redde"
- "edde" gets mangled to "edde edde"
- "ede" gets mangled to "ede ede"

But:
- "Reddmann" does not get mangled
- "Redmann" does not get mangled
- "Reemann" does not get mangled 

So it seems like the strings "edde" and "ede" are the problem. Any idea what could be causing this?? I'm happy to help debug if you can tell me where to look.

**Comment by girzel** [comment]
Ugh, the name parsing code needs to be rewritten, I think with a proper parser instead of a pile of regular expressions. This has been on my list for a while now, but obviously we're hitting regressions so I will bump up the priority. Thanks for the report.

**Comment by franburstall** [comment]
More on this: `ebdb-divide-name` splits the surname on any match of `ebdb-lastname-prefixes` *no matter where it occurs in the string*.  Thus
```emacs-lisp
(ebdb-divide-name "George Holderforce")
```
yields
```emacs-lisp
("rforth" ("George") nil "Holde")
```
One should probably test for prefixes only at the start of surnames and maybe separated by spaces from the rest?

**Comment by girzel** [comment]
Sorry for the very long wait here! And thanks to @franburstall for identifying the problem. I've been trying out a fancier parsing library to solve this and other issues, in order to avoid the regexp hairball issue. So far I haven't been able to make that work, though, and it's fairly clear how to fix this problem, so I'm just adding to the hairball for now. This fix will be out with a new point release in the next day or so. Thanks again.

**Comment by wyleyr** [comment]
This is great, thanks so much to you both for your efforts!
