### ISSUE TITLE
C-x s doesn't save ebdb file

### ISSUE THREAD

**Issue by tromey** [girzel/ebdb#52]
I noticed that `C-x s` did not save the ebdb file.  However, exiting emacs did save it.  I think it would be nice if it were treated more like an ordinary file in this way.

**Comment by girzel** [comment]
I've actually got a patch pending for Emacs core that would allow this -- right now `save-some-buffers` won't touch `special-mode` buffers, because they are not visiting a file. EBDB buffers don't visit files, and I can't pretend they do, because records might be drawn from multiple databases. My patch (which was inspired particularly by this problem with EBDB) would allow `save-some-buffers` to ignore the lack of a buffer-file, so long as `write-contents-functions` was non-nil.

I hope that eventually gets applied.

**Comment by tromey** [comment]
Wow, thanks for doing that.
